// <auto-generated />
using System;
using LandingDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandingDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandingDB.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Fecha_Contacto")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_contacto");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nombre_Apellido")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_apellido");

                    b.HasKey("Id");

                    b.ToTable("Contacto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
